version: '3'
services: 
  web:
    image: chmey/kanweek:latest
    build: backend
    ports:
        - "5000:5000"
    depends_on:
        - db
  db:
    image: mongo
    expose:
      - 27017
    ports:
      - 27017:27017